### ISSUE TITLE
GearmanWorker fails with 'Failed to set exception option'

### ISSUE THREAD

**Issue by tboloo** [johnewart/gearman-java#3]
Setup:
```
vagrant@planq:~$ php -i | grep gearman
/etc/php5/cli/conf.d/20-gearman.ini, gearman
gearman support => enabled
libgearman version => 1.1.12
Gearman PECL => gearman 1.1.2 stable
gearman-server 0.8.9-SNAPSHOT
```

## Worker app.
```
<?php
$worker= new GearmanWorker();
$worker->addServer("192.168.130.16", 4730);
$worker->addFunction("reverse", "my_reverse_function");
while ($worker->work()); 
function my_reverse_function($job) {
  return strrev($job->workload());
}
?>
```

```
vagrant@planq:~$ php worker.php 
PHP Fatal error:  Uncaught exception 'GearmanException' with message 'Failed to set exception option' in /home/vagrant/worker.php:3
Stack trace:
#0 /home/vagrant/worker.php(3): GearmanWorker->addServer('192.168.130.16', 4730)
#1 {main}
  thrown in /home/vagrant/worker.php on line 3
```
And following error in server:
```
10:15:02.762 - [nioEventLoopGroup-3-2] DEBUG n.j.gearman.server.net.PacketHandler - Creating new handler!
10:15:02.762 - [nioEventLoopGroup-3-2] ERROR n.j.g.common.packets.PacketFactory - Unhandled type: 
10:15:02.763 - [nioEventLoopGroup-3-2] WARN  n.j.gearman.server.net.PacketHandler - Unexpected exception from downstream.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:415) ~[gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:334) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:320) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:497) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:465) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:359) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.lang.NullPointerException: null
	at net.johnewart.gearman.server.net.Decoder.decode(Decoder.java:60) ~[gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:360) ~[gearman-server-0.8.9-20141210.162656-1.jar:0.4]
	... 10 common frames omitted
10:15:02.764 - [nioEventLoopGroup-3-2] DEBUG n.j.gearman.server.net.PacketHandler - Client closed channel: [id: 0x89bba760, /192.168.130.16:59106 :> 0.0.0.0/0.0.0.0:4730]
10:15:03.637 - [pool-2-thread-1] DEBUG n.j.g.s.u.SnapshottingJobQueueMonitor - Snapshotting job queues.
10:15:03.638 - [pool-2-thread-1] DEBUG n.j.g.s.u.SnapshottingJobQueueMonitor - Condensing data points
```

**Comment by johnewart** [comment]
This should be fixed in 371cd8da433fad266fa0452898d89b96e07d4276 - I added support to handle OPTION_REQ packets and send back a corresponding OPTION_RES - tested with the Ruby library. Can you let me know if this is fixed?

**Comment by tboloo** [comment]
Call me stupid, but where do I find 0.8.10-SNAPSHOT version? It's not in https://oss.sonatype.org/content/repositories/snapshots/net/johnewart/gearman/gearman-server/ ?

**Comment by johnewart** [comment]
I haven't built a new version and pushed it, I'll do that tomorrow. In the meantime you can use the source release and build it with maven if you need it.

**Comment by tboloo** [comment]
OK, I am waiting then.

**Comment by tboloo** [comment]
Any chances for a new version soon?

**Comment by johnewart** [comment]
Just had a chance to release a new build - https://oss.sonatype.org/content/repositories/snapshots/net/johnewart/gearman/gearman-server/0.8.10-SNAPSHOT/

**Comment by tboloo** [comment]
It all fine and dandy now, thanks!

**Comment by icewing02** [comment]
Hey there, am pretty much new here. But how did you install the snapshot? I am having the same error. I am using MAMP. Thanks.

**Comment by tboloo** [comment]
As John posted you can find the snapshots [here](https://oss.sonatype.org/content/repositories/snapshots/net/johnewart/gearman/gearman-server/0.8.10-SNAPSHOT/).
You do not need MAMP to run the server, only java, as per instructions [here](https://github.com/johnewart/gearman-java#getting-started)
